### ISSUE TITLE
No html5 output on build

### ISSUE THREAD

**Issue by arasouli91** [mikesmullin/vcpp11-sdl2-emscripten-wasm#1]
I ran build but the html5 folder is empty.

So I tried to run the command from the batch file in cmd and I got this:

WARNING:root:retrieving port: zlib from https://github.com/emscripten-ports/zlib/archive/version_1.zip
Traceback (most recent call last):
  File "D:\prog\emsdk-portable-64bit\emscripten\1.37.35\\emcc", line 10, in <module>
    python_selector.run(__file__, profile=True)
  File "D:\prog\emsdk-portable-64bit\emscripten\1.37.35\tools\python_selector.py", line 43, in run
    sys.exit(run_by_import(filename, main) if on_allowed_version() else run_by_subprocess(filename))
  File "D:\prog\emsdk-portable-64bit\emscripten\1.37.35\tools\python_selector.py", line 13, in run_by_import
    return getattr(importlib.import_module(os.path.basename(filename)), main)()
  File "D:\prog\emsdk-portable-64bit\emscripten\1.37.35\emcc.py", line 1387, in run
    compile_source_file(i, input_file)
  File "D:\prog\emsdk-portable-64bit\emscripten\1.37.35\emcc.py", line 1377, in compile_source_file
    args = get_bitcode_args([input_file]) + ['-emit-llvm', '-c', '-o', output_file]
  File "D:\prog\emsdk-portable-64bit\emscripten\1.37.35\emcc.py", line 1360, in get_bitcode_args
    args = system_libs.process_args(args, shared.Settings)
  File "D:\prog\emsdk-portable-64bit\emscripten\1.37.35\tools\system_libs.py", line 766, in process_args
    args = port.process_args(Ports, args, settings, shared)
  File "D:\prog\emsdk-portable-64bit\emscripten\1.37.35\tools\ports\zlib.py", line 51, in process_args
    get(ports, settings, shared)
  File "D:\prog\emsdk-portable-64bit\emscripten\1.37.35\tools\ports\zlib.py", line 17, in get
    ports.fetch_project('zlib', 'https://github.com/emscripten-ports/zlib/archive/' + TAG + '.zip', 'zlib-' + TAG)
  File "D:\prog\emsdk-portable-64bit\emscripten\1.37.35\tools\system_libs.py", line 676, in fetch_project
    retrieve()
  File "D:\prog\emsdk-portable-64bit\emscripten\1.37.35\tools\system_libs.py", line 639, in retrieve
    f = urlopen(url)
  File "D:\prog\emsdk-portable-64bit\python\2.7.5.3_64bit\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "D:\prog\emsdk-portable-64bit\python\2.7.5.3_64bit\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "D:\prog\emsdk-portable-64bit\python\2.7.5.3_64bit\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "D:\prog\emsdk-portable-64bit\python\2.7.5.3_64bit\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "D:\prog\emsdk-portable-64bit\python\2.7.5.3_64bit\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "D:\prog\emsdk-portable-64bit\python\2.7.5.3_64bit\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>

I have no idea what this means. Help would be greatly appreciated.

**Comment by mikesmullin** [comment]
sorry i can't offer this support. can only say it worked for me at the time.
